version: "3"
services:
  ui:
    build: ./TalkGPT.UI
    ports:
      - "5173:80"
    depends_on: [web]
  web:
    build: ./TalkGPT.Server
    ports:
      - "3000:3000"
    depends_on: [db]
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: TALK
      MYSQL_PASSWORD: Password123
      MYSQL_DATABASE: TALKGPT
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./sql-scripts/script.sql:/docker-entrypoint-initdb.d/1.sql
