CREATE TABLE CHAT (
    ID INT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MESSAGE (
    ID INT PRIMARY KEY,
    CHAT_ID INT,
    ROLE NVARCHAR(10) NOT NULL,
    CONTENT NVARCHAR(5000) NOT NULL,
    AUDIO NVARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CHAT_ID) REFERENCES CHAT(ID)
);